name: Server CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  AWS_EC2_HOST: ${{ vars.AWS_EC2_HOST }}
  AWS_EC2_USERNAME: ${{ vars.AWS_EC2_USERNAME }}
  AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: SETUP - checkout repository
        uses: actions/checkout@v2

      - name: SETUP - set up node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: DEPLOY
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.AWS_EC2_HOST }}
          username: ${{ env.AWS_EC2_USERNAME }}
          key: ${{ env.AWS_EC2_KEY }}
          script: |
            cd xrwa-server

            pm2 stop 0
            pm2 delete 0

            yarn prisma:push
            yarn build

            pm2 start yarn --interpreter bash --name "xrwa-server" -- start
